### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by dfayzur** [yaysummeriscoming/DALI_pytorch_demo#1]
@yaysummeriscoming : Thank you very much for the repo and the blog post for explaining how to work with DALI for productivity. It is very helpful.

Could you please put a LICENCE file, so that I can use it in my project?

Thanks in advance!

**Comment by yaysummeriscoming** [comment]
Great to hear, just added the license file.

**Comment by dfayzur** [comment]
Thank you very much.
