### ISSUE TITLE
how to improve cpu usage?

### ISSUE THREAD

**Issue by Edwardmark** [yaysummeriscoming/DALI_pytorch_demo#6]
Hi, I noticed that the cpu usage is up to 400%, how can I make it larger to improve the training speed?
should I change the maxsize larger?
https://github.com/yaysummeriscoming/DALI_pytorch_demo/blob/master/dali.py#L306
And I have multiple gpus, how to make it run faster? 
Looking forward to your reply.

**Comment by yaysummeriscoming** [comment]
What type of CPU are you using? I got best performance by setting the number of dataloader workers to num_cpu_cores - 2, which in my case was 10.

You shouldn't need to change any other params, like that queue size.

**Comment by Edwardmark** [comment]
@yaysummeriscoming so you can get full cpu usage?

**Comment by yaysummeriscoming** [comment]
yes

**Comment by yaysummeriscoming** [comment]
Have you also checked GPU utilization using nvidia-smi?

**Comment by Edwardmark** [comment]
@yaysummeriscoming  GPU usage is high near 100%, but cpu usage is low. I use CPU dali to train a resnet50 model using fp32.

**Comment by yaysummeriscoming** [comment]
Then your GPU is the bottleneck, not the CPU based data pipeline. This level of CPU usage is normal then
